added my project for xcode 13
iOS-vk-education/2023_1_-MyCar pull request #3
Opened 2023-10-31 22:19 UTC by lizzardvpidzhake322

Надеюсь, все правильно сделал и у тебя всё соберется. На верстку не смотри, потом все переделаем, просто хотел показать, как мы примерно будем вести проект. Таблица рабочая, можно что-нибудь добавить, потом доведем её до нужного нам вида)

2023-11-02 17:21 UTC, Sharinant requested changes

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsViewController.swift
> +        view as! MyCarsView
Нет смысла создавать еще один объект, если решили отделять View от ViewController, то просто создавай 
`private let contentView = MyCarsView()`

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsViewController.swift
> +        view as! MyCarsView
var*

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +        self.backgroundColor = .yellow
Лучше сделать отдельный не приватный метод `func setup() {
setupAddCarButton...
}` и его дергать из VC

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +        self.backgroundColor = .yellow
В VC в методе viewDidLayoutSubviews

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +    var carsMas = [CellContent]()
Просто cars 
В названиях не использовать Array Massiv Set и тд

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: CarCellTableViewCell.identifier, for: indexPath)
Ячейки вот так делать лучше, чтобы неопциональные были
`guard let cell = tableView.dequeueReusableCell(
                    withReuseIdentifier: ...,
                    for: indexPath)
                    as? CarCellTableViewCell else {
                return UITableViewCell()
            }`
            Тут же конфигурируешь эту ячейку и ее отдаешь

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +struct CellContent {
В отдельный файл

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsViewController.swift
> +            guard let carName = carField.text, !carName.isEmpty else{
Тут еще надо запретить ввод цифр 

Вообще ввод марки и модели авто я бы сделал через picker 
С бека какого-нибудь получать список марок и моделей можно

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/TabBarController.swift
> +    private func setupViewControllers(vC: UIViewController, image: UIImage?) -> UIViewController {
либо назвать setImage или как-то так 

либо вообще убрать этот метод и ставить просто 

https://github.com/Sharinant/ios---musicExpress/blob/main/MusicExpress/Controllers/Core/TabBarViewController.swift

Например, так 
Тут не идеально) но посмотреть можно

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsViewController.swift
> +        let alert = UIAlertController(title: "Добавить новую машину", message: "Напишите марку новой машины", preferredStyle: .alert)
Мы вроде же хотели отдельный экран добавления машины?

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +//  MainScreenView.swift
Тут переименуй

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/TabBarController.swift
> +    private func setupViewControllers(vC: UIViewController, image: UIImage?) -> UIViewController {
И добавить mapVC

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +import UIKit
Тут напишу общие штуки
Убрать сториборд
И раскидать все аккуратно по папкам

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +import UIKit
myCarrrr и myCars отделить? Либо проект переименовать, либо назвать Garage

2023-11-02 17:21 UTC, Sharinant commented on MyCar/MyCarrrr/MyCars/MyCarsView.swift
> +    var carsMas = [CellContent]()
И я бы тогда уж в модель вынес данные 

Можно сделать Apple MVC тогда

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Views/MyCarsView.swift
>          let customCell = cell as? CarCellTableViewCell
` guard let cell = tableView.dequeueReusableCell( withIdentifier: CarCellTableViewCell.identifier, for: indexPath) as? CarCellTableViewCell else { return UITableViewCell() }
cell.update(with..)
return cell`

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
> +    private var contentView = MyCarsView()
тут let

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
>          view = MyCarsView()
тут присвой contentView

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Views/MyCarsView.swift
> +        cars.remove(at: index)
по поводу разделения сущностей
давайте сделаем модель и прокинем ее во viewController
оттуда протоколом будем говорить, что мы делаем с данными
чтобы view ничего не делала с данными

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Model/CarModel.swift
> +struct CellContent {
надо согласовать, что это) CarModel или CellContent 
Название файла, объекта и комментария сверху одинаковые должны быть

И давайте не carMark, а типа manufacturer

2023-11-09 10:40 UTC, Sharinant commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
>      private func addCar() {
так это тут или на отдельном экране?

2023-11-09 11:54 UTC, Sharinant commented on MyCar/MyCarrrr/Views/MyCarsView.swift
> +        cars.remove(at: index)
но не меняй пока ничего в плане архитектуры

2023-11-09 11:55 UTC, Sharinant commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
>      private func addCar() {
как я понял это в другой ветке?

2023-11-13 10:01 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Views/MyCarsView.swift
>          let customCell = cell as? CarCellTableViewCell
Не совсем понимаю, в чем тут проблема( 
Можно подробнее в лс тогда?

2023-11-13 10:01 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
> +    private var contentView = MyCarsView()
Исправил

2023-11-13 10:01 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
>          view = MyCarsView()
Исправил

2023-11-13 10:02 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Views/MyCarsView.swift
> +        cars.remove(at: index)
Пока не совсем понимаю, как правильно реализовать прокид модели

2023-11-13 10:02 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Model/CarModel.swift
> +struct CellContent {
Пока просто поменял название поля

2023-11-13 10:02 UTC, lizzardvpidzhake322 commented on MyCar/MyCarrrr/Controllers/MyCarsViewController.swift
>      private func addCar() {
Не пойму, про что ты тут?

2023-11-13 16:39 UTC, Sharinant approved these changes

2023-11-13 16:39 UTC, merged